import logging
from bs4 import BeautifulSoup
from datetime import datetime
import sys
import os

# --- Add project root to path ---
project_root = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, project_root)

from services.config import Config
from services.signal_parser import SignalParser

# --- Setup ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


class HtmlSignalExtractor:
    """
    A specialist tool to parse a saved HTML file from Discord, extract messages,
    and generate a backtesting signal log.
    """

    def __init__(self, config):
        self.config = config
        # We use our battle-hardened parser, the "translator"
        self.parser = SignalParser(self.config)

    def extract_signals_from_html(self, input_html_path: str, output_txt_path: str):
        """
        Reads an HTML file, finds messages, parses them, and writes valid
        signals to a text file in the backtester format.
        """
        logger.info(f"Opening HTML file: {input_html_path}")
        try:
            with open(input_html_path, 'r', encoding='utf-8') as f:
                soup = BeautifulSoup(f, 'html.parser')
        except FileNotFoundError:
            logger.critical(f"FATAL: The input file was not found at '{input_html_path}'")
            return

        # Reconnaissance: Find all message containers. Discord often uses <li> elements
        # with a specific class for messages. This may need adjustment if Discord changes its HTML.
        # We look for a class that is unique to message list items.
        message_elements = soup.find_all('li')
        logger.info(f"Found {len(message_elements)} potential message elements. Analyzing...")

        found_signals = 0
        with open(output_txt_path, 'w', encoding='utf-8') as out_f:
            out_f.write("# Auto-generated by html_to_signals.py\n")
            out_f.write("# Format: YYYY-MM-DD HH:MM:SS | The exact signal text from Discord\n\n")

            for element in message_elements:
                # Find the message content within the element
                content_div = element.find("div", class_=lambda c: c and c.startswith("messageContent"))
                # Find the timestamp, often stored in an accessible way
                time_tag = element.find("time")

                if content_div and time_tag and time_tag.has_attr('datetime'):
                    message_text = content_div.get_text(strip=True)
                    timestamp_iso = time_tag['datetime']
                    
                    # --- The Gatekeeper ---
                    # Use our "translator" to see if this is a valid trade signal
                    parsed_signal = self.parser.parse_signal_message(message_text, {})
                    
                    if parsed_signal:
                        # --- The Scribe ---
                        # Convert ISO format timestamp to our backtester format
                        dt_obj = datetime.fromisoformat(timestamp_iso.replace('Z', '+00:00'))
                        formatted_timestamp = dt_obj.strftime('%Y-%m-%d %H:%M:%S')
                        
                        # Write the valid signal to our battle plan
                        output_line = f"{formatted_timestamp} | {message_text}\n"
                        out_f.write(output_line)
                        logger.info(f"FOUND SIGNAL: {output_line.strip()}")
                        found_signals += 1

        logger.info("-" * 30)
        logger.info(f"Extraction complete. Found {found_signals} valid signals.")
        logger.info(f"Battle plan saved to: {output_txt_path}")
        logger.info("-" * 30)


def main():
    """Main entry point for the script."""
    # Define the input and output file paths
    # You will save your webpage as 'discord_export.html' in the main project folder
    input_file = "discord_export.html"
    output_file = "backtester/signals_to_test.txt"

    # Create a placeholder input file if it doesn't exist
    if not os.path.exists(input_file):
        with open(input_file, 'w') as f:
            f.write("<!-- Save your Discord channel's HTML content here -->\n")
            f.write("<!-- In Chrome, right-click on the page and select 'Save as...' -->\n")
            f.write("<!-- Choose 'Webpage, Complete' and name it discord_export.html -->")
        logger.info(f"Created a sample input file at: {input_file}")
        logger.info("Please save your Discord page to this file and run the script again.")
        return

    extractor = HtmlSignalExtractor(Config())
    extractor.extract_signals_from_html(input_file, output_file)

if __name__ == "__main__":
    main()
```

### **How to Use Your New Tool**

1.  **Save Your Web Page:** Go to the Discord channel you want to backtest in your Chrome browser. Right-click anywhere on the page and select **"Save as..."**.
2.  In the "Save as type" dropdown, choose **"Webpage, Complete"**.
3.  Name the file exactly **`discord_export.html`** and save it in your main `Discord_To_IBKR_3` project folder.
4.  **Run the Extractor:** Open your clean Command Prompt, make sure your `(venv)` is active, and run this one simple command:
    ```cmd
    python html_to_signals.py
    
